//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRebelsRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterRebelds
    {
        public int Id { get; set; }
        public int IdRebeld { get; set; }
        public int IdPlanet { get; set; }
        public System.DateTime DateRegsiter { get; set; }
    
        public virtual Planets Planets { get; set; }
        public virtual Rebelds Rebelds { get; set; }
    }
}
